### ISSUE TITLE
Preferred Single Quote doesn't allow me to use double quotes, even in content

### ISSUE THREAD

**Issue by felipenmoura** [rossPatton/stylint#271]
Hi.
I am using the stylint with Preferred Single Quote enabled.
But it fails on this code:

```css
seletor:after {
    content: '"'; // " between '
}
```

It should allow me to use in that situation.
It still blocks it even if I scape it with \", and using `&quote;` will not work either.

What am I supposed to do? Disable this validation?!

Thanks.
