### ISSUE TITLE
Validity is not properly checking rules proceeding closing curly brace

### ISSUE THREAD

**Issue by awayken** [rossPatton/stylint#63]
If a line of Stylus code ends with a curly brace, the code is not properly checked for validity. I was able to specify made up properties, use invalid values and even just type text that doesn't follow CSS rules at all.

invalid.styl
```stylus
// Passes but shouldn't
body { dog: irish-setter; banana: brown; hair-length: 10em; Lorem ipsum }
body {
    dog: irish-setter; banana: brown; hair-length: 10em; Lorem ipsum }

// Fails and should
body {
    dog: irish-setter; banana: brown; hair-length: 10em; Lorem ipsum
}
body {
    dog: irish-setter;
    banana: brown;
    hair-length: 10em;
    Lorem ipsum
}
```

invalid.json
```json
{
    "alphabetical": true,
    "borderNone": true,
    "brackets": false,
    "colons": false,
    "colors": false,
    "commaSpace": true,
    "commentSpace": false,
    "cssLiteral": false,
    "depthLimit": false,
    "duplicates": true,
    "efficient": true,
    "enforceBlockStyle": false,
    "enforceVarStyle": false,
    "extendPref": false,
    "globalDupe": false,
    "indentSpaces": 4,
    "leadingZero": true,
    "maxWarnings": 10,
    "maxWarningsKill": false,
    "mixed": false,
    "namingConvention": false,
    "parenSpace": false,
    "placeholders": true,
    "semicolons": false,
    "universal": true,
    "valid": true,
    "whitespace": true,
    "zeroUnits": true,
    "zIndexDuplicates": false,
    "zIndexNormalize": false
}
```

Output:
```bash
Warning:  property is not valid
File: invalid.styl
Line: 8: dog: irish-setter; banana: brown; hair-length: 10em; Lorem ipsum

Warning:  property is not valid
File: invalid.styl
Line: 11: dog: irish-setter;

Warning:  property is not valid
File: invalid.styl
Line: 12: banana: brown;

Warning:  property is not valid
File: invalid.styl
Line: 13: hair-length: 10em;

Warning:  property is not valid
File: invalid.styl
Line: 14: Lorem ipsum


5 Warnings
```

I think an interesting testament to how crucial this project is when you look at how Stylus itself treats this same file. It doesn't care at all. It goes right ahead and changes the file into what it thinks is CSS.

invalid.css
```css
body {
  dog: irish-setter;
  banana: #a52a2a;
  hair-length: 10em;
  Lorem: ipsum;
}
body {
  dog: irish-setter;
  banana: #a52a2a;
  hair-length: 10em;
  Lorem: ipsum;
}
body {
  dog: irish-setter;
  banana: #a52a2a;
  hair-length: 10em;
  Lorem: ipsum;
}
body {
  dog: irish-setter;
  banana: #a52a2a;
  hair-length: 10em;
  Lorem: ipsum;
}
```

It's never been more clear to me how important and useful Stylint is for maintaining and writing sane, valid and professional Stylus code.
